<form method="post">
    <div class="form-group">
        <label for="name">Team Name</label>
        <input id="name" type="text" class="form-control" name="name" value="" placeholder="Enter team name">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<?php if (isset($this->isValid)) {?>
    <?php if ($this->isValid) {?>
        <div class="alert alert-success" role="alert">The team is created successfully!</div>
    <?php } else {?>
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <?php echo $this->message?>
        </div>
    <?php }?>
<?php }?>
</form>