<?php echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']); ?>
<div class="date-nav">
  <a href="<?php echo $this->url('team', ['action' => 'add']) ?>" class="btn btn-primary right"><?php echo $this->t->translate('team.add') ?></a>
  <div class="clear"></div>
</div>
<table id="team-table" class="table display" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>ID</th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('fees.due') ?> (￥)</th>
    <th><?php echo $this->t->translate('fees.paid') ?> (￥)</th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </thead>
  <tbody>
  <?php if ($this->teams->count()) { ?>
      <?php foreach ($this->teams as $team) { ?>
      <tr>
        <td><?php echo $team->id ?></td>
        <td><?php echo $team->name ?></td>
        <td><?php echo round($this->fees[$team->id], 2) ?></td>
        <td><?php echo round($this->feesPaid[$team->id], 2) ?></td>
        <td><a href="<?php echo $this->url('team', ['action' => 'edit', 'id' => $team->id]) ?>" class="btn btn-primary"><?php echo $this->t->translate('edit') ?></a></td>
      </tr>
      <?php } ?>
  <?php } ?>
  </tbody>
  <tfoot>
  <tr>
    <th>ID</th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('fees.due') ?> (￥)</th>
    <th><?php echo $this->t->translate('fees.paid') ?> (￥)</th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </tfoot>
</table>