<?php echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']); ?>
<form method="post">
  <fieldset>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="username"><?php echo $this->t->translate('user.name') ?></label>
      </div>
      <input type="text" class="form-control" disabled value="<?php echo $this->user->username ?>" placeholder="Enter username">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="teamId"><?php echo $this->t->translate('team.name') ?></label>
      </div>
      <select <?php echo $this->userObject->isManager() ? 'name="teamId"' : 'disabled' ?> class="form-control">
        <option value="0"> - <?php echo $this->t->translate('select.team') ?> -</option>
          <?php foreach ($this->teams as $team) { ?>
            <option <?php echo $team->id == $this->user->teamId ? 'selected' : '' ?>
                value="<?php echo $team->id ?>"><?php echo $team->name ?></option>
          <?php } ?>
      </select>
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="password"><?php echo $this->t->translate('password') ?></label>
      </div>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="confirm_password"><?php echo $this->t->translate('confirm.password') ?></label>
      </div>
      <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('submit') ?></button>
    </div>
  </fieldset>
</form>
<?php if (isset($this->isValid)) { ?>
  <?php if ($this->isValid) { ?>
  <div class="alert alert-success" role="alert">Password reset!</div>
  <?php } else { ?>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
      <?php echo $this->message ?>
  </div>
  <?php } ?>
<?php } ?>