<?php echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']); ?>
<table id="team-table" class="table display" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th><?php echo $this->t->translate('user.name') ?></th>
        <th><?php echo $this->t->translate('team.name') ?></th>
        <th><?php echo $this->t->translate('edit') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if ($this->users->count()) { ?>
        <?php foreach ($this->users as $user) { ?>
            <tr>
                <td><?php echo $user->username ?></td>
                <td><?php echo $user->team ?></td>
                <td>
                    <a href="<?php echo $this->url('user', ['action' => 'edit', 'id' => $user->username]) ?>" class="btn btn-primary">Edit</a>
                </td>
            </tr>
        <?php } ?>
    <?php } ?>
    </tbody>
    <tfoot>
    <tr>
      <th><?php echo $this->t->translate('user.name') ?></th>
      <th><?php echo $this->t->translate('team.name') ?></th>
      <th><?php echo $this->t->translate('edit') ?></th>
    </tr>
    </tfoot>
</table>