<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
<form method="post">
  <fieldset>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="username"><?php echo $this->t->translate('user.name') ?></label>
      </div>
      <input type="text" class="form-control" name="username" value="" placeholder="Enter username">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="password"><?php echo $this->t->translate('password') ?></label>
      </div>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('login') ?></button>
    </div>
  </fieldset>
</form>