<form method="post">
  <fieldset>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="username"><?php echo $this->t->translate('user.name') ?></label>
      </div>
      <input type="text" class="form-control" name="username" value="" placeholder="Enter username">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="password"><?php echo $this->t->translate('password') ?></label>
      </div>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="confirm_password"><?php echo $this->t->translate('confirm.password') ?></label>
      </div>
      <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('submit') ?></button>
    </div>
  </fieldset>
</form>
<?php if (isset($this->isValid)) {?>
<?php if ($this->isValid) {?>
<div class="alert alert-success" role="alert">The user is registered successfully!</div>
<?php } else {?>
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  <?php echo $this->message?>
</div>
<?php }?>
<?php }?>
</form>