<?php if (!$this->team) {?>
<form method="get">
  <fieldset>
    <legend></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="select-team"><?php echo $this->t->translate('select.team') ?></label>
      </div>
      <select onselect="this.form.submit();" id="select-team" class="form-control" name="teamId">
        <option value=""> - <?php echo $this->t->translate('select.team') ?> - </option>
          <?php foreach ($this->teams as $team) {?>
            <option value="<?php echo $team->id ?>"><?php echo $team->name ?></option>
          <?php }?>
      </select>
      <input type="hidden" name="type" value="<?php echo $this->type ?>">
    </div>
    <div class="input-group">
      <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('next') ?></button>
    </div>
  </fieldset>
</form>
<?php } else {?>
<form method="post">
  <div class="input-group">
    <h4><span class="badge badge-secondary"><?php echo $this->t->translate('team.name') ?></span> <?php echo $this->team->name ?></h4>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <label class="input-group-text" for="itemName"><?php echo $this->t->translate('item.name') ?></label>
    </div>
    <input <?php echo $this->product ? 'disabled' : '' ?> id="itemName" data-url="inventory/get-item-names" placeholder="Enter item name" name="itemName" value="<?php echo $this->product ? $this->product->itemName : '' ?>" type="text" class="form-control ui-autocomplete-input">
  </div>
  <fieldset>
    <legend><?php echo $this->t->translate('product.info') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="brand"><?php echo $this->t->translate('brand.name') ?></label>
      </div>
      <input <?php echo $this->brand ? 'disabled' : '' ?> id="brand" data-url="inventory/get-brand-names" placeholder="Enter brand name" name="brand" value="<?php echo $this->brand ? $this->brand->name : '' ?>" type="text" class="form-control ui-autocomplete-input">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="qty"><?php echo $this->t->translate('qty') ?></label>
      </div>
      <input id="qty" name="qty" value="" type="number" min="0" <?php echo $this->type == 'out' ? 'max="' . $this->product->qty . '"' : '' ?> class="form-control">
      <?php if ($this->type == 'out') { ?>
      <div class="input-group-prepend">
        <label class="input-group-text" for="qty"><?php echo '<em>(' . $this->t->translate('maximum') . $this->product->qty . ')</em>' ?></label>
      </div>
      <?php }?>
    </div>
    <div class="clear"></div>
    <div class="input-group textarea">
      <div class="input-group-prepend">
        <label class="input-group-text" for="note"><?php echo $this->t->translate('note') ?></label>
      </div>
      <textarea style="width: 800px;height: 150px;" id="note" name="note" class="form-control"></textarea>
    </div>
  </fieldset>
  <?php if ($this->type == 'in') {?>
  <fieldset>
    <legend><?php echo $this->t->translate('size') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="length"><?php echo $this->t->translate('length') ?></label>
      </div>
      <input id="length" name="length" value="<?php echo $this->product ? $this->product->length : '' ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="width"><?php echo $this->t->translate('width') ?></label>
      </div>
      <input id="width" name="width" value="<?php echo $this->product ? $this->product->width : '' ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="height"><?php echo $this->t->translate('height') ?></label>
      </div>
      <input id="height" name="height" value="<?php echo $this->product ? $this->product->height : '' ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="weight"><?php echo $this->t->translate('weight') ?></label>
      </div>
      <input id="weight" name="weight" value="<?php echo $this->product ? $this->product->weight : '' ?>" type="text" class="form-control">
    </div>
  </fieldset>
  <?php }?>
  <button type="submit" class="btn btn-primary"><?php echo $this->type == 'out' ? $this->t->translate('next') : $this->t->translate('submit') ?></button>
</form>
<?php if (!empty($this->message)) { ?>
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  <?php echo $this->message ?>
</div>
<?php } ?>
<link href="<?php echo $this->basePath('js/jquery-ui-1.12.1.custom/jquery-ui.theme.min.css') ?>" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.12.1.custom/jquery-ui.min.js') ?>"></script>
<?php }?>
