<?php echo $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?php echo $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<form method="post">
  <fieldset>
    <legend></legend>
    <div class="input-group">
      <h4><span class="badge badge-secondary"><?php echo $this->t->translate('team.name') ?></span> <?php echo $this->team->name ?></h4>
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="amount"><?php echo $this->t->translate('amount') ?></label>
      </div>
      <input placeholder="Enter amount" name="amount" value="" type="number" class="form-control ui-autocomplete-input">
      <div class="input-group-prepend">
        <label class="input-group-text" for="amount"><em>(<?php echo $this->t->translate('fees.due') ?>: ￥<?php echo $this->amountDue ?>)</label>
      </div>
    </div>
    <div class="input-group">
      <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('submit') ?></button>
    </div>
  </fieldset>
</form>