<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
<form method="post">
  <div class="form-group">
    <label>Business Team:</label> <?php echo $this->team->name ?>
  </div>
  <div class="form-group">
    <label for="itemName">Item Name</label>
    <input id="itemName" data-url="inventory/get-item-names" placeholder="Enter item name" name="itemName" value="<?php echo $this->product->itemName ?>" type="text" class="form-control ui-autocomplete-input">
  </div>
  <fieldset>
    <legend>Product Info</legend>
    <div class="form-group">
      <label for="brand">Brand</label>
      <input id="brand" data-url="inventory/get-brand-names" placeholder="Enter brand name" name="brand" value="<?php echo $this->brand->name ?>" type="text" class="form-control ui-autocomplete-input">
    </div>
  </fieldset>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<link href="<?php echo $this->basePath('js/jquery-ui-1.12.1.custom/jquery-ui.theme.min.css') ?>" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.12.1.custom/jquery-ui.min.js') ?>"></script>

