<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
<form method="post">
  <div class="input-group">
    <h4><span class="badge badge-secondary"><?php echo $this->t->translate('team.name') ?></span> <?php echo $this->team->name ?></h4>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <label class="input-group-text" for="itemName"><?php echo $this->t->translate('item.name') ?></label>
    </div>
    <input id="itemName" data-url="inventory/get-item-names" placeholder="Enter item name" name="itemName" value="<?php echo $this->product->itemName ?>" type="text" class="form-control ui-autocomplete-input">
  </div>
  <fieldset>
    <legend><?php echo $this->t->translate('product.info') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="brand"><?php echo $this->t->translate('brand.name') ?></label>
      </div>
      <input id="brand" data-url="inventory/get-brand-names" placeholder="Enter brand name" name="brand" value="<?php echo $this->brand->name ?>" type="text" class="form-control ui-autocomplete-input">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="qty"><?php echo $this->t->translate('qty') ?></label>
      </div>
      <input id="qty" name="qty" min="0" <?php echo $this->package->type == 'out' ? 'max="' . $this->product->qty . '"' : '' ?> value="<?php echo $this->package->qty ?>" type="number" class="form-control">
      <?php if ($this->package->type == 'out') { ?>
        <div class="input-group-prepend">
          <label class="input-group-text" for="qty"><?php echo '<em>(' . $this->t->translate('maximum') . $this->product->qty . ')</em>' ?></label>
        </div>
      <?php }?>
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="note"><?php echo $this->t->translate('note') ?></label>
      </div>
      <input id="note" name="note" value="<?php echo $this->package->note ?>" type="text" class="form-control">
      <div class="input-group-prepend">
        <label class="input-group-text" for="note"><em>(<?php echo $this->t->translate('optional') ?>)</em></label>
      </div>
    </div>
  </fieldset>
  <fieldset>
    <legend><?php echo $this->t->translate('size') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="length"><?php echo $this->t->translate('length') ?></label>
      </div>
      <input id="length" name="length" value="<?php echo $this->package->length ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="width"><?php echo $this->t->translate('width') ?></label>
      </div>
      <input id="width" name="width" value="<?php echo $this->package->width ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="height"><?php echo $this->t->translate('height') ?></label>
      </div>
      <input id="height" name="height" value="<?php echo $this->package->height ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="weight"><?php echo $this->t->translate('weight') ?></label>
      </div>
      <input id="weight" name="weight" value="<?php echo $this->package->weight ?>" type="text" class="form-control">
    </div>
  </fieldset>
  <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('submit') ?></button>
</form>
<link href="<?php echo $this->basePath('js/jquery-ui-1.12.1.custom/jquery-ui.theme.min.css') ?>" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.12.1.custom/jquery-ui.min.js') ?>"></script>

