<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<div class="date-nav">
  <a href="<?php echo $this->url('inventory', ['action' => 'add'], ['query' => ['type' => 'in']]) ?>" class="btn btn-primary right" style="margin-right:10px;"><?php echo $this->t->translate('receive.new.package') ?></a>
  <div class="clear"></div>
</div>
<table id="package-table" class="table display" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>ID</th>
    <th><?php echo $this->t->translate('process.type') ?></th>
    <th><?php echo $this->t->translate('status') ?></th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('qty') ?></th>
    <th><?php echo $this->t->translate('size') ?></th>
    <th><?php echo $this->t->translate('weight') ?></th>
    <th><?php echo $this->t->translate('date') ?></th>
    <th><?php echo $this->t->translate('note') ?></th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </thead>
  <tbody>
  <?php if ($this->packages->count()) { ?>
      <?php foreach ($this->packages as $package) { ?>
      <tr>
        <td><?php echo $package->id ?></td>
        <td><?php echo $package->renderProcessType() ?></td>
        <td><?php echo $package->renderStatus() ?></td>
        <td><?php echo $package->team ?></td>
        <td><?php echo $package->itemName ?></td>
        <td><?php echo $package->brand ?></td>
        <td><?php echo $package->qty ?></td>
        <td><?php echo $package->renderSize() ?></td>
        <td><?php echo $package->weight ?></td>
        <td><?php echo $package->processDate ?></td>
        <td><?php echo $package->note ?></td>
        <td class="actions">
          <?php if ($package->type == 'out') { ?>
          <a href="<?php echo $this->url('inventory', ['action' => 'view', 'id' => $package->id]) ?>" class="btn btn-info"><?php echo $this->t->translate('view') ?></a>
          <?php }?>
          <a href="<?php echo $this->url('inventory', ['action' => 'edit', 'id' => $package->id]) ?>" class="btn btn-primary"><?php echo $this->t->translate('edit') ?></a>
          <a href="<?php echo $this->url('inventory', ['action' => 'delete', 'id' => $package->id]) ?>" class="btn btn-danger"><?php echo $this->t->translate('delete') ?></a>
        </td>
      </tr>
      <?php } ?>
  <?php } ?>
  </tbody>
  <tfoot>
  <tr>
    <th>ID</th>
    <th><?php echo $this->t->translate('process.type') ?></th>
    <th><?php echo $this->t->translate('status') ?></th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('qty') ?></th>
    <th><?php echo $this->t->translate('size') ?></th>
    <th><?php echo $this->t->translate('weight') ?></th>
    <th><?php echo $this->t->translate('date') ?></th>
    <th><?php echo $this->t->translate('note') ?></th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </tfoot>
</table>