<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>

<?php if ($this->userObject->isManager()) { ?>
<link href="<?php echo $this->basePath('js/jquery-ui-1.12.1.custom/jquery-ui.theme.min.css') ?>" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.12.1.custom/jquery-ui.min.js') ?>"></script>

<div class="date-nav">
  <form id="search" class="left" method="get">
    <input type="hidden" name="type" value="<?php echo $this->type ?>">
    <input type="submit" style="display: none;" />
    <?php if ($this->type == 'out') {?>
    <a id="download-invoice" href="javascript:void(0);" class="btn btn-success dropdown-filter"><?php echo $this->t->translate('download.invoice') ?></a>
    <?php }?>
    <button class="btn btn-primary dropdown-filter" type="submit"><?php echo $this->t->translate('submit') ?></button>
    <div class="input-group dropdown-filter">
      <div class="input-group-prepend">
        <label class="input-group-text" for="select-team"><?php echo $this->t->translate('select.team') ?></label>
      </div>
      <select onselect="this.form.submit();" id="select-team" class="form-control" name="teamId">
        <option value=""> - </option>
        <?php foreach ($this->teams as $team) {?>
        <option <?php echo $this->teamId == $team->id ? 'selected' : '' ?> value="<?php echo $team->id ?>"><?php echo $team->name ?></option>
        <?php }?>
      </select>
    </div>
    <?php if ($this->type == 'out') {?>
    <div class="input-group dropdown-filter">
      <div class="input-group-prepend">
        <label class="input-group-text" for="select-carrier"><?php echo $this->t->translate('shipping.carrier') ?></label>
      </div>
      <select onselect="this.form.submit();" id="select-carrier" class="form-control" name="carrier">
        <option value=""> - </option>
        <?php foreach ($this->carriers as $carrier) {?>
        <option <?php echo $this->carrier == $carrier ? 'selected' : '' ?> value="<?php echo $carrier ?>"><?php echo $carrier ?></option>
        <?php }?>
      </select>
    </div>
    <?php }?>
    <div class="input-group dropdown-filter">
      <div class="input-group-prepend">
        <label class="input-group-text" for="itemName"><?php echo $this->t->translate('item.name') ?></label>
      </div>
      <input id="itemName" data-url="inventory/get-item-names" name="itemName" value="<?php echo $this->itemName ?>" type="text" class="form-control ui-autocomplete-input">
    </div>
  </form>
  <?php if ($this->type == 'in') { ?>
  <a href="<?php echo $this->url('inventory', ['action' => 'add'], ['query' => ['type' => 'in']]) ?>" class="btn btn-primary right" style="margin-right:10px;">+<?php echo $this->t->translate('receive.package') ?></a>
  <?php }?>
  <div class="clear"></div>
</div>
<?php }?>
<table id="package-table-<?php echo $this->type ?>" class="table display" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>ID</th>
    <?php if ($this->type == 'out') { ?>
    <th><?php echo $this->t->translate('status') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('qty') ?></th>
    <th><?php echo $this->t->translate('case.qty') ?></th>
    <th><?php echo $this->t->translate('size') ?></th>
    <th><?php echo $this->t->translate('weight') ?></th>
    <?php if ($this->type == 'out') { ?>
    <?php if ($this->userObject->isManager()) {?>
    <th><?php echo $this->t->translate('shipping.cost') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('shipping.fee') ?></th>
    <th><?php echo $this->t->translate('service.fee') ?></th>
    <th><?php echo $this->t->translate('customs') ?></th>
    <th><?php echo $this->t->translate('shipping.carrier') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('date') ?></th>
    <th><?php echo $this->t->translate('note') ?></th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </thead>
  <tbody>
  <?php if ($this->packages->count()) { ?>
      <?php foreach ($this->packages as $package) { ?>
      <tr>
        <td class="packageId"><?php echo $package->id ?></td>
        <?php if ($this->type == 'out') { ?>
        <td><?php echo $package->renderStatus() ?></td>
        <?php }?>
        <td><?php echo $package->team ?></td>
        <td><?php echo $package->itemName ?></td>
        <td><?php echo $package->brand ?></td>
        <td><?php echo $package->qty ?></td>
        <td><?php echo $package->caseQty ?></td>
        <td><?php echo $package->renderSize() ?></td>
        <td><?php echo $package->weight ?></td>
        <?php if ($this->type == 'out') { ?>
        <?php if ($this->userObject->isManager()) {?>
        <td><?php echo round($package->shippingCost, 2) ?></td>
        <?php }?>
        <td><?php echo round($package->shippingFee, 2) ?></td>
        <td><?php echo round($package->serviceFee, 2) ?></td>
        <td><?php echo round($package->customs, 2) ?></td>
        <td><?php echo $package->carrier ?></td>
        <?php }?>
        <td><?php echo $package->processDate ?></td>
        <td><?php echo $package->note ?></td>
        <td class="actions">
          <?php if ($package->type == 'out') { ?>
          <a href="<?php echo $this->url('inventory', ['action' => 'view', 'id' => $package->id]) ?>" class="btn btn-info"><?php echo $this->t->translate('view') ?></a>
          <?php } else {?>
          <a href="<?php echo $this->url('inventory', ['action' => 'edit', 'id' => $package->id]) ?>" class="btn btn-info"><?php echo $this->t->translate('package.info') ?></a>
          <?php }?>
        </td>
      </tr>
      <?php } ?>
  <?php } ?>
  </tbody>
  <tfoot>
  <tr>
    <th>ID</th>
    <?php if ($this->type == 'out') { ?>
    <th><?php echo $this->t->translate('status') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('qty') ?></th>
    <th><?php echo $this->t->translate('case.qty') ?></th>
    <th><?php echo $this->t->translate('size') ?></th>
    <th><?php echo $this->t->translate('weight') ?></th>
    <?php if ($this->type == 'out') { ?>
    <?php if ($this->userObject->isManager()) {?>
    <th><?php echo $this->t->translate('shipping.cost') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('shipping.fee') ?></th>
    <th><?php echo $this->t->translate('service.fee') ?></th>
    <th><?php echo $this->t->translate('customs') ?></th>
    <th><?php echo $this->t->translate('shipping.carrier') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('date') ?></th>
    <th><?php echo $this->t->translate('note') ?></th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </tfoot>
</table>