<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>

<?php if ($this->userObject->isManager()) { ?>
  <div class="date-nav">
    <form id="search" class="left" method="get">
      <input type="submit" style="display: none;" />
      <button class="btn btn-primary dropdown-filter" type="submit"><?php echo $this->t->translate('submit') ?></button>
      <div class="input-group dropdown-filter">
        <div class="input-group-prepend">
          <label class="input-group-text" for="select-team"><?php echo $this->t->translate('select.team') ?></label>
        </div>
        <select onselect="this.form.submit();" id="select-team" class="form-control" name="teamId">
          <option value=""> - </option>
            <?php foreach ($this->teams as $team) {?>
              <option <?php echo $this->teamId == $team->id ? 'selected' : '' ?> value="<?php echo $team->id ?>"><?php echo $team->name ?></option>
            <?php }?>
        </select>
      </div>
      <div class="input-group dropdown-filter">
        <div class="input-group-prepend">
          <label class="input-group-text" for="itemName"><?php echo $this->t->translate('item.name') ?></label>
        </div>
        <input id="itemName" data-url="inventory/get-item-names" name="itemName" value="<?php echo $this->itemName ?>" type="text" class="form-control ui-autocomplete-input">
      </div>
    </form>
    <div class="clear"></div>
  </div>
<?php }?>
<table id="product-table" class="table display" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th>ID</th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('qty') ?></th>
    <?php if ($this->userObject->isManager()) {?>
    <th><?php echo $this->t->translate('shipping.cost') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('shipping.fee') ?></th>
    <th><?php echo $this->t->translate('service.fee') ?></th>
    <th><?php echo $this->t->translate('customs') ?></th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </thead>
  <tbody>
  <?php if ($this->products->count()) { ?>
      <?php foreach ($this->products as $product) { ?>
      <tr>
        <td><?php echo $product->id ?></td>
        <td><?php echo $product->team ?></td>
        <td><?php echo $product->itemName ?></td>
        <td><?php echo $product->brand ?></td>
        <td><?php echo $product->qty ?></td>
        <?php if ($this->userObject->isManager()) {?>
        <td><?php echo round($this->feeList[$product->id]->shippingCost, 2) ?></td>
        <?php }?>
        <td><?php echo round($this->feeList[$product->id]->shippingFee, 2) ?></td>
        <td><?php echo round($this->feeList[$product->id]->serviceFee, 2) ?></td>
        <td><?php echo round($this->feeList[$product->id]->customs, 2) ?></td>
        <td class="actions">
          <?php if ($this->userObject->isManager()) {?>
          <a href="<?php echo $this->url('inventory', ['action' => 'add', 'id' => $product->id], ['query' => ['type' => 'in']]) ?>" class="btn btn-primary">+<?php echo $this->t->translate('receive.package') ?></a>
          <?php }
          if ($product->qty > 0) {?>
          <a href="<?php echo $this->url('inventory', ['action' => 'add', 'id' => $product->id], ['query' => ['type' => 'out']]) ?>" class="btn btn-success"><?php echo $this->t->translate('ship.package.request') ?></a>
          <?php }?>
          <a href="<?php echo $this->url('inventory', ['action' => 'edit-product', 'id' => $product->id]) ?>" class="btn btn-primary"><?php echo $this->t->translate('edit') ?></a>
        </td>
      </tr>
      <?php } ?>
  <?php } ?>
  </tbody>
  <tfoot>
  <tr>
    <th>ID</th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('qty') ?></th>
    <?php if ($this->userObject->isManager()) {?>
    <th><?php echo $this->t->translate('shipping.cost') ?></th>
    <?php }?>
    <th><?php echo $this->t->translate('shipping.fee') ?></th>
    <th><?php echo $this->t->translate('service.fee') ?></th>
    <th><?php echo $this->t->translate('customs') ?></th>
    <th><?php echo $this->t->translate('actions') ?></th>
  </tr>
  </tfoot>
</table>
<script>
$(function() {
    $('.delete').click(function(e) {
        e.preventDefault();
        if (!confirm('<?php echo $this->t->translate('product.delete.confirm'); ?>')) {
            return;
        }
        location.href = $(this).attr('href');
    });
})
</script>