<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
<table class="table display" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th><?php echo $this->t->translate('item.name') ?></th>
    <th><?php echo $this->t->translate('team.name') ?></th>
    <th><?php echo $this->t->translate('brand.name') ?></th>
    <th><?php echo $this->t->translate('package.id') ?></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><?php echo $this->product->itemName ?></td>
    <td><?php echo $this->team->name ?></td>
    <td><?php echo $this->brand->name ?></td>
    <td><?php echo $this->package->id ?></td>
  </tr>
  </tbody>
</table>
<form id="shippingForm" method="post" enctype="multipart/form-data">
  <fieldset>
    <legend><?php echo $this->t->translate('package.info') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="qty"><?php echo $this->t->translate('qty') ?></label>
      </div>
      <input id="qty" name="qty" value="<?php echo $this->package->qty ?>" type="number" min="0" max="<?php echo $this->product->qty + $this->package->qty ?>" class="form-control">
      <div class="input-group-prepend">
        <label class="input-group-text" for="qty"><em>(<?php echo $this->t->translate('maximum') . ($this->product->qty + $this->package->qty) ?>)</em></label>
      </div>
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="caseQty"><?php echo $this->t->translate('case.qty') ?></label>
      </div>
      <input id="caseQty" name="caseQty" value="<?php echo $this->package->caseQty ?>" type="number" min="0" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="status"><?php echo $this->t->translate('status') ?></label>
      </div>
      <select class="custom-select" id="status" <?php echo $this->userObject->isManager() ? 'name="status"' : 'disabled ' ?>>
          <?php foreach ($this->statusList as $value => $info) {?>
            <option <?php echo $this->package->status == $value ? 'selected' : '' ?> value="<?php echo $value ?>"><?php echo $this->t->translate($info['label']) ?></option>
          <?php }?>
      </select>
    </div>
    <div class="clear"></div>
    <div class="input-group textarea">
      <div class="input-group-prepend">
        <label class="input-group-text" for="note"><?php echo $this->t->translate('note') ?></label>
      </div>
      <textarea style="width: 800px;height: 150px;" id="note" name="note" class="form-control"><?php echo $this->package->note ?></textarea>
    </div>
  </fieldset>
  <fieldset>
    <legend><?php echo $this->t->translate('size') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="length"><?php echo $this->t->translate('length') ?></label>
      </div>
      <input id="length" <?php echo $this->userObject->isManager() ? 'name="length"' : 'disabled ' ?> value="<?php echo $this->package->length ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="width"><?php echo $this->t->translate('width') ?></label>
      </div>
      <input id="width" <?php echo $this->userObject->isManager() ? 'name="width"' : 'disabled ' ?> value="<?php echo $this->package->width ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="height"><?php echo $this->t->translate('height') ?></label>
      </div>
      <input id="height" <?php echo $this->userObject->isManager() ? 'name="height"' : 'disabled ' ?> value="<?php echo $this->package->height ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="weight"><?php echo $this->t->translate('weight') ?></label>
      </div>
      <input id="weight" <?php echo $this->userObject->isManager() ? 'name="weight"' : 'disabled ' ?> value="<?php echo $this->package->weight ?>" type="text" class="form-control">
    </div>
  </fieldset>
  <fieldset>
    <legend><?php echo $this->t->translate('process.requirements') ?></legend>
    <table id="requirements-table" class="table display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <?php foreach ($this->requirements as $field => $label) {?>
          <th>
            <div class="form-check">
              <input <?php echo $this->shipping->$field ? 'checked' : '' ?> id="<?php echo $field ?>" name="<?php echo $field ?>" value="1" type="checkbox" class="form-check-input">
              <label for="<?php echo $field ?>"><?php echo $this->t->translate($label) ?></label>
            </div>
          </th>
          <?php }?>
        </tr>
      </thead>
      <tbody>
        <tr>
          <?php foreach ($this->requirements as $field => $label) {?>
          <td id="<?php echo $field ?>-preview">0</td>
          <?php }?>
        </tr>
      </tbody>
    </table>
  </fieldset>
  <fieldset>
    <legend><?php echo $this->t->translate('fees') ?></legend>
    <?php if ($this->userObject->isManager()) {?>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="shippingCost"><?php echo $this->t->translate('shipping.cost') ?></label>
      </div>
      <input id="shippingCost" name="shippingCost" value="<?php echo round($this->shipping->shippingCost, 2) ?>" type="text" class="form-control">
    </div>
    <?php }?>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="shippingFee"><?php echo $this->t->translate('shipping.fee') ?></label>
      </div>
      <input id="shippingFee" <?php echo $this->userObject->isManager() ? 'name="shippingFee"' : 'disabled ' ?> value="<?php echo round($this->shipping->shippingFee, 2) ?>" type="text" class="form-control">
    </div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="serviceFee"><?php echo $this->t->translate('service.fee') ?></label>
      </div>
      <input id="serviceFee" disabled value="<?php echo round($this->shipping->serviceFee, 2) ?>" type="text" class="form-control">
    </div>
  </fieldset>
  <fieldset>
    <legend><?php echo $this->t->translate('customs') ?></legend>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="customs"><?php echo $this->t->translate('customs.amount') ?></label>
      </div>
      <input id="customs" <?php echo $this->userObject->isManager() ? 'name="customs"' : 'disabled ' ?> value="<?php echo round($this->shipping->customs, 2) ?>" type="text" class="form-control">
    </div>
    <div class="input-group full-size">
      <div class="input-group-prepend">
        <label class="input-group-text" for="customsNumber"><?php echo $this->t->translate('customs.number') ?></label>
      </div>
      <input id="customsNumber" <?php echo $this->userObject->isManager() ? 'name="customsNumber"' : 'disabled ' ?> value="<?php echo $this->shipping->customsNumber ?>" type="text" class="form-control">
    </div>
  </fieldset>
  <?php if ($this->userObject->isManager() || !empty($this->address)) {?>
  <fieldset>
    <legend><?php echo $this->t->translate('shipping.info') ?></legend>
    <?php
    $fields = [
        'recipient' => 'recipient',
        'phone' => 'phone',
        'zip' => 'zip',
        'country' => 'country',
    ];
    ?>
    <?php foreach ($fields as $field => $label) {?>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="<?php echo $field ?>"><?php echo $this->t->translate($label) ?></label>
      </div>
      <input id="<?php echo $field ?>" <?php echo $this->userObject->isManager() ? 'name="' . $field . '"' : 'disabled ' ?> value="<?php echo $this->address->$field ?>" type="text" class="form-control">
    </div>
    <?php }?>
    <div class="clear"></div>
    <div class="input-group textarea">
      <div class="input-group-prepend">
        <label class="input-group-text" for="address"><?php echo $this->t->translate('address') ?></label>
      </div>
      <textarea style="width:800px;height: 150px;" id="address" <?php echo $this->userObject->isManager() ? 'name="address"' : 'disabled ' ?> class="form-control"><?php echo $this->address->address ?></textarea>
    </div>
    <div class="clear"></div>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="carrier"><?php echo $this->t->translate('shipping.carrier') ?></label>
      </div>
      <input id="carrier" <?php echo $this->userObject->isManager() ? 'name="carrier"' : 'disabled ' ?> value="<?php echo $this->shipping->carrier ?>" type="text" class="form-control">
    </div>
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-prepend">
          <label class="input-group-text" for="trackingNumber"><?php echo $this->t->translate('tracking.number') ?></label>
        </div>
        <input id="trackingNumber" <?php echo $this->userObject->isManager() ? 'name="trackingNumber"' : 'disabled ' ?> value="<?php echo $this->shipping->trackingNumber ?>" type="text" class="form-control">
      </div>
    </div>
    <div class="clear"></div>
  </fieldset>
  <?php }?>
  <fieldset>
    <legend><?php echo $this->t->translate('attachments') ?></legend>
    <?php foreach ($this->attachments as $field => $langKey) {?>
    <div class="input-group" style="width: 60%;">
      <div class="input-group-prepend">
        <label class="input-group-text" for="<?php echo $field ?>"><?php echo $this->t->translate($langKey) ?></label>
      </div>
      <input id="<?php echo $field ?>" name="<?php echo $field ?>" type="file" class="form-control">
      <?php if ($this->shipping->$field) {?>
      <div class="input-group-prepend">
        <label class="input-group-text" for="<?php echo $field ?>"><a target="_blank" href="<?php echo $this->basePath($this->shipping->getAttachment($field)) ?>"><?php echo $this->shipping->$field ?></a></label>
      </div>
      <?php }?>
    </div>
    <?php }?>
  </fieldset>
  <button type="submit" class="btn btn-primary"><?php echo $this->t->translate('submit') ?></button>
</form>
<?php if (!empty($this->message)) { ?>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
      <?php echo $this->message ?>
  </div>
<?php } ?>